# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kurs.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1187, 805)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.nameFilm1 = QtWidgets.QLabel(self.centralwidget)
        self.nameFilm1.setObjectName("nameFilm1")
        self.horizontalLayout_2.addWidget(self.nameFilm1)
        self.lineFilm1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFilm1.setObjectName("lineFilm1")
        self.horizontalLayout_2.addWidget(self.lineFilm1)
        self.buttonSerch = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSerch.setObjectName("buttonSerch")
        self.horizontalLayout_2.addWidget(self.buttonSerch)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.listFilms = QtWidgets.QListWidget(self.centralwidget)
        self.listFilms.setObjectName("listFilms")
        self.verticalLayout.addWidget(self.listFilms)
        self.clearList = QtWidgets.QPushButton(self.centralwidget)
        self.clearList.setObjectName("clearList")
        self.verticalLayout.addWidget(self.clearList)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 5, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Type1 = QtWidgets.QLabel(self.centralwidget)
        self.Type1.setObjectName("Type1")
        self.horizontalLayout_3.addWidget(self.Type1)
        self.Type3 = QtWidgets.QComboBox(self.centralwidget)
        self.Type3.setEditable(False)
        self.Type3.setObjectName("Type3")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.Type3.addItem("")
        self.horizontalLayout_3.addWidget(self.Type3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.searchYears = QtWidgets.QLabel(self.centralwidget)
        self.searchYears.setObjectName("searchYears")
        self.verticalLayout_3.addWidget(self.searchYears)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.firstYear = QtWidgets.QLineEdit(self.centralwidget)
        self.firstYear.setObjectName("firstYear")
        self.horizontalLayout.addWidget(self.firstYear)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.secondYear = QtWidgets.QLineEdit(self.centralwidget)
        self.secondYear.setObjectName("secondYear")
        self.horizontalLayout.addWidget(self.secondYear)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.collect = QtWidgets.QPushButton(self.centralwidget)
        self.collect.setObjectName("collect")
        self.verticalLayout_3.addWidget(self.collect)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameFilm2 = QtWidgets.QLabel(self.centralwidget)
        self.nameFilm2.setObjectName("nameFilm2")
        self.verticalLayout_2.addWidget(self.nameFilm2)
        self.lineFilm2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFilm2.setObjectName("lineFilm2")
        self.verticalLayout_2.addWidget(self.lineFilm2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.year = QtWidgets.QLineEdit(self.centralwidget)
        self.year.setObjectName("year")
        self.verticalLayout_2.addWidget(self.year)
        self.Type2 = QtWidgets.QLabel(self.centralwidget)
        self.Type2.setObjectName("Type2")
        self.verticalLayout_2.addWidget(self.Type2)
        self.Type4 = QtWidgets.QComboBox(self.centralwidget)
        self.Type4.setEditable(False)
        self.Type4.setObjectName("Type4")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.Type4.addItem("")
        self.verticalLayout_2.addWidget(self.Type4)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.produsser = QtWidgets.QLineEdit(self.centralwidget)
        self.produsser.setObjectName("produsser")
        self.verticalLayout_2.addWidget(self.produsser)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AddTofile = QtWidgets.QPushButton(self.centralwidget)
        self.AddTofile.setObjectName("AddTofile")
        self.verticalLayout_4.addWidget(self.AddTofile)
        self.clearLine = QtWidgets.QPushButton(self.centralwidget)
        self.clearLine.setObjectName("clearLine")
        self.verticalLayout_4.addWidget(self.clearLine)
        self.gridLayout.addLayout(self.verticalLayout_4, 4, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1187, 26))
        self.menubar.setObjectName("menubar")
        self.menu_3_0 = QtWidgets.QMenu(self.menubar)
        self.menu_3_0.setObjectName("menu_3_0")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu_3_0.addSeparator()
        self.menubar.addAction(self.menu_3_0.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameFilm1.setText(_translate("MainWindow", "Название фильма"))
        self.buttonSerch.setText(_translate("MainWindow", "Поиск"))
        self.clearList.setText(_translate("MainWindow", "Очистить список"))
        self.Type1.setText(_translate("MainWindow", "Жанр"))
        self.Type3.setItemText(0, _translate("MainWindow", "аниме"))
        self.Type3.setItemText(1, _translate("MainWindow", "любой"))
        self.Type3.setItemText(2, _translate("MainWindow", "фэнтези"))
        self.Type3.setItemText(3, _translate("MainWindow", "мелодрама"))
        self.Type3.setItemText(4, _translate("MainWindow", "биография"))
        self.Type3.setItemText(5, _translate("MainWindow", "боевик"))
        self.Type3.setItemText(6, _translate("MainWindow", "вестерн"))
        self.Type3.setItemText(7, _translate("MainWindow", "военный"))
        self.Type3.setItemText(8, _translate("MainWindow", "детектив"))
        self.Type3.setItemText(9, _translate("MainWindow", "документальный"))
        self.Type3.setItemText(10, _translate("MainWindow", "драма"))
        self.Type3.setItemText(11, _translate("MainWindow", "мультфильм"))
        self.Type3.setItemText(12, _translate("MainWindow", "приключения"))
        self.Type3.setItemText(13, _translate("MainWindow", "семейный"))
        self.Type3.setItemText(14, _translate("MainWindow", "триллер"))
        self.Type3.setItemText(15, _translate("MainWindow", "ужасы"))
        self.Type3.setItemText(16, _translate("MainWindow", "фантастика"))
        self.searchYears.setText(_translate("MainWindow", "Поиск по годам"))
        self.label_3.setText(_translate("MainWindow", "С"))
        self.label_5.setText(_translate("MainWindow", "до"))
        self.collect.setText(_translate("MainWindow", "Подобрать"))
        self.label_6.setText(_translate("MainWindow", " Добавить свой фильм"))
        self.nameFilm2.setText(_translate("MainWindow", "Название фильма"))
        self.label_8.setText(_translate("MainWindow", "Год выпуска"))
        self.Type2.setText(_translate("MainWindow", "Жанр"))
        self.Type4.setItemText(0, _translate("MainWindow", "аниме"))
        self.Type4.setItemText(1, _translate("MainWindow", "любой"))
        self.Type4.setItemText(2, _translate("MainWindow", "фэнтези"))
        self.Type4.setItemText(3, _translate("MainWindow", "мелодрама"))
        self.Type4.setItemText(4, _translate("MainWindow", "биография"))
        self.Type4.setItemText(5, _translate("MainWindow", "боевик"))
        self.Type4.setItemText(6, _translate("MainWindow", "вестерн"))
        self.Type4.setItemText(7, _translate("MainWindow", "военный"))
        self.Type4.setItemText(8, _translate("MainWindow", "детектив"))
        self.Type4.setItemText(9, _translate("MainWindow", "документальный"))
        self.Type4.setItemText(10, _translate("MainWindow", "драма"))
        self.Type4.setItemText(11, _translate("MainWindow", "мультфильм"))
        self.Type4.setItemText(12, _translate("MainWindow", "приключения"))
        self.Type4.setItemText(13, _translate("MainWindow", "семейный"))
        self.Type4.setItemText(14, _translate("MainWindow", "триллер"))
        self.Type4.setItemText(15, _translate("MainWindow", "ужасы"))
        self.Type4.setItemText(16, _translate("MainWindow", "фантастика"))
        self.label_9.setText(_translate("MainWindow", "Режиссёр"))
        self.AddTofile.setText(_translate("MainWindow", "Добавить фильм в список"))
        self.clearLine.setText(_translate("MainWindow", "Очистить поля ввода"))
        self.menu_3_0.setTitle(_translate("MainWindow", "Кинопрокат3.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
